# Generated by Django 5.2.16 on 2026-07-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classcourseassignment',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='截止日期'),
        ),
    ]
