# Generated by Django 5.2.16 on 2026-07-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_accountdeletionrequest_previous_class_group_and_more'),
        ('courses', '0003_normalize_lecture_inline_math'),
        ('interactions', '0006_remove_studentsubmission_assignment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assignmentquestion',
            name='uq_assignment_question',
        ),
        migrations.RemoveConstraint(
            model_name='classcourse',
            name='uq_class_course',
        ),
        migrations.RemoveField(
            model_name='assignmentquestion',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='classcourseassignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='classcourse',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='classcourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='classcourseassignment',
            name='class_course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '讲义系列', 'verbose_name_plural': '讲义系列'},
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentQuestion',
        ),
        migrations.DeleteModel(
            name='ClassGroup',
        ),
        migrations.DeleteModel(
            name='ClassCourse',
        ),
        migrations.DeleteModel(
            name='ClassCourseAssignment',
        ),
    ]
