# Generated by Django 5.2.16 on 2026-07-30 23:06

import django.db.models.deletion
from django.db import migrations, models


def seed_video_categories(apps, schema_editor):
    VideoCategory = apps.get_model('courses', 'VideoCategory')
    categories = (
        ('系列系统课程', '围绕完整知识体系制作的连续课程。'),
        ('专题深度解析', '针对具体问题或知识点进行深入讲解。'),
        ('学习经验分享', '分享学习方法、备考经验和成长经历。'),
        ('学术交流', '围绕数学、教育及相关学术问题开展讨论。'),
    )
    for index, (name, description) in enumerate(categories, start=1):
        VideoCategory.objects.update_or_create(
            name=name,
            defaults={'description': description, 'sort_order': index * 10},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_assignmentquestion_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '视频分类',
                'verbose_name_plural': '视频分类',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('cover_url', models.URLField(blank=True, default='', max_length=500, verbose_name='封面地址')),
                ('platform_name', models.CharField(blank=True, default='', max_length=64, verbose_name='发布平台')),
                ('video_url', models.URLField(max_length=500, verbose_name='视频地址')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_published', models.BooleanField(default=False, verbose_name='已上架')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='courses.videocategory')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ('category__sort_order', 'sort_order', '-published_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VideoDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_label', models.CharField(blank=True, default='', help_text='如“配套讲解”“例题演示”“拓展内容”', max_length=64, verbose_name='关联说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.document')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.video')),
            ],
            options={
                'verbose_name': '视频讲义关联',
                'verbose_name_plural': '视频讲义关联',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='video',
            name='documents',
            field=models.ManyToManyField(related_name='videos', through='courses.VideoDocumentLink', to='courses.document'),
        ),
        migrations.AddConstraint(
            model_name='videodocumentlink',
            constraint=models.UniqueConstraint(fields=('video', 'document'), name='unique_video_document_link'),
        ),
        migrations.RunPython(seed_video_categories, migrations.RunPython.noop),
    ]
