"""
Django settings for math_platform project.

Generated by 'django-admin startproject' using Django 5.2.16.
"""

from pathlib import Path
from datetime import timedelta

from decouple import config
from django.core.exceptions import ImproperlyConfigured
from django.db.backends.signals import connection_created

BASE_DIR = Path(__file__).resolve().parent.parent

ENVIRONMENT = config('ENVIRONMENT', default='development').strip().lower()
IS_PRODUCTION = ENVIRONMENT == 'production'


def require_production_value(name, value, *, min_length=1):
    """Reject missing or placeholder secrets before production starts."""
    normalized = value.strip()
    weak_values = {'', 'change-me', 'dev-pdf-key-for-testing'}
    if normalized in weak_values or len(normalized) < min_length:
        raise ImproperlyConfigured(
            f'{name} must be set to a strong production value',
        )
    return normalized


SECRET_KEY = config(
    'SECRET_KEY',
    default=(
        '' if IS_PRODUCTION else
        'JXliDAnEPHiqqhud0fE7drCjVILqOSY85lN01fqUCBGcSPJyub1xQqoCK70zKaok6Cg'
    ),
)
if IS_PRODUCTION:
    SECRET_KEY = require_production_value(
        'SECRET_KEY', SECRET_KEY, min_length=50,
    )

DEBUG = config('DEBUG', default=not IS_PRODUCTION, cast=bool)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured('DEBUG must be False in production')

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='' if IS_PRODUCTION else 'localhost,127.0.0.1',
    cast=lambda v: [s.strip() for s in v.split(',')],
)
ALLOWED_HOSTS = [host for host in ALLOWED_HOSTS if host]
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('ALLOWED_HOSTS must be set in production')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'whitenoise',
    'drf_spectacular',
    'auditlog',
    'accounts',
    'qbank',
    'courses',
    'interactions',
    'system',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'math_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'math_platform.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
        'OPTIONS': {
            'timeout': 20,
            'transaction_mode': 'IMMEDIATE',
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.'
        'NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


def enable_wal(sender, connection, **kwargs):
    if connection.vendor == 'sqlite':
        cursor = connection.cursor()
        cursor.execute('PRAGMA journal_mode=WAL;')
        cursor.execute('PRAGMA synchronous=NORMAL;')
        cursor.execute('PRAGMA busy_timeout=20000;')
        # 默认 wal_autocheckpoint=1000（每~4MB自动 checkpoint），防止 WAL 膨胀
        # 显式设置以确保行为一致
        cursor.execute('PRAGMA wal_autocheckpoint=1000;')


connection_created.connect(enable_wal)

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000',
    cast=lambda v: [s.strip() for s in v.split(',')],
)
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.'
        'JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS':
        'drf_spectacular.openapi.AutoSchema',
    'EXCEPTION_HANDLER':
        'math_platform.exceptions.custom_exception_handler',
}

# ── Security / CSRF / Proxy ──
# Cloudflare Tunnel terminates TLS at edge, nginx receives HTTP.
# Tell Django the original scheme was HTTPS via proxy header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = config(
    'SECURE_SSL_REDIRECT', default=False, cast=bool,
)
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_HSTS_SECONDS = config(
    'SECURE_HSTS_SECONDS',
    default=3600 if IS_PRODUCTION else 0,
    cast=int,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://zhangyuzhixue.top,https://zhangyuzhixue.zhtec123.com',
    cast=lambda v: [s.strip() for s in v.split(',')],
)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'CHECK_REVOKE_TOKEN': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'zhangyuzhixue API',
    'DESCRIPTION': 'zhangyuzhixue v2 API',
    'VERSION': '1.0.0',
}

SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    import sentry_sdk
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        traces_sample_rate=config(
            'SENTRY_TRACES_SAMPLE_RATE',
            default=0.1,
            cast=float,
        ),
    )

# PDF 签名密钥（生产环境通过环境变量设置）
PDF_SECRET_KEY = config(
    'PDF_SECRET_KEY',
    default='' if IS_PRODUCTION else 'dev-pdf-key-for-testing',
)
if IS_PRODUCTION:
    PDF_SECRET_KEY = require_production_value(
        'PDF_SECRET_KEY', PDF_SECRET_KEY, min_length=32,
    )
