# Generated by Django 5.2.16 on 2026-07-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='学号'),
        ),
    ]
