# Generated by Django 5.2.16 on 2026-07-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='显示名称'),
        ),
    ]
