# Generated by Django 5.2.16 on 2026-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='data_version',
            field=models.IntegerField(default=0, verbose_name='数据版本'),
        ),
    ]
