# Generated by Django 5.2.16 on 2026-07-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def repair_legacy_foreign_keys(apps, schema_editor):
    """Apply the SET_NULL/CASCADE outcomes missed by historical SQLite data."""
    User = apps.get_model('auth', 'User')
    InvitationCode = apps.get_model('accounts', 'InvitationCode')
    ClassCourse = apps.get_model('courses', 'ClassCourse')
    ClassCourseAssignment = apps.get_model(
        'courses', 'ClassCourseAssignment',
    )

    valid_class_courses = ClassCourse.objects.values('pk')
    ClassCourseAssignment.objects.exclude(
        class_course_id__in=valid_class_courses,
    ).delete()

    valid_users = User.objects.values('pk')
    InvitationCode.objects.filter(
        used_by_id__isnull=False,
    ).exclude(used_by_id__in=valid_users).update(used_by_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_data_version'),
        ('courses', '0002_alter_classcourseassignment_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            repair_legacy_foreign_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='student',
            name='account_status',
            field=models.CharField(
                choices=[
                    ('active', '正常'),
                    ('pending_deletion', '待注销'),
                    ('anonymized', '已匿名化'),
                ],
                db_index=True,
                default='active',
                max_length=24,
                verbose_name='账号状态',
            ),
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID',
                )),
                ('status', models.CharField(
                    choices=[
                        ('pending', '冷静期内'),
                        ('cancelled', '已撤销'),
                        ('anonymized', '已匿名化'),
                    ],
                    db_index=True,
                    default='pending',
                    max_length=16,
                    verbose_name='状态',
                )),
                ('requested_at', models.DateTimeField(verbose_name='申请时间')),
                ('scheduled_for', models.DateTimeField(
                    db_index=True, verbose_name='计划匿名化时间',
                )),
                ('cancelled_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='撤销时间',
                )),
                ('anonymized_at', models.DateTimeField(
                    blank=True, null=True, verbose_name='匿名化时间',
                )),
                ('previous_class_group', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+', to='courses.classgroup',
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='deletion_request',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': '账号注销申请',
                'verbose_name_plural': '账号注销申请',
            },
        ),
    ]
