# Generated by Django 5.2.16 on 2026-07-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationConsent',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID',
                )),
                ('terms_version', models.CharField(
                    max_length=32, verbose_name='用户协议版本',
                )),
                ('privacy_version', models.CharField(
                    max_length=32, verbose_name='隐私政策版本',
                )),
                ('source', models.CharField(
                    default='student_app', max_length=32, verbose_name='来源',
                )),
                ('accepted_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='同意时间',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='registration_consents',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': '注册协议同意记录',
                'verbose_name_plural': '注册协议同意记录',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
