# Generated by Django 5.2.16 on 2026-07-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_unique_nonempty_student_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdeletionrequest',
            name='previous_class_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_group',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
