# Generated by Django 5.2.16 on 2026-07-28 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='板块名称')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='地址标识')),
                ('summary', models.CharField(max_length=240, verbose_name='板块说明')),
                ('status', models.CharField(choices=[('active', '正常运行'), ('internal_test', '内部测试'), ('in_progress', '开发中'), ('pending', '待确认'), ('paused', '暂停维护'), ('retired', '已下线'), ('archived', '历史资料')], default='active', max_length=24, verbose_name='状态')),
                ('is_visible', models.BooleanField(default=True, verbose_name='显示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '业务板块',
                'verbose_name_plural': '业务板块',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='章鱼智学项目中心', max_length=80, verbose_name='门户标题')),
                ('positioning', models.CharField(max_length=240, verbose_name='项目定位')),
                ('current_phase', models.CharField(blank=True, max_length=160, verbose_name='当前阶段')),
                ('current_focus', models.TextField(blank=True, verbose_name='当前重点')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目概览',
                'verbose_name_plural': '项目概览',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='姓名')),
                ('responsibility', models.CharField(blank=True, max_length=160, verbose_name='主要职责')),
                ('is_active', models.BooleanField(default=True, verbose_name='在团队中')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PortalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('entry_type', models.CharField(choices=[('product', '产品'), ('download', '下载'), ('media', '自媒体'), ('document', '文档'), ('tool', '工具'), ('service', '服务')], max_length=20, verbose_name='类型')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('status', models.CharField(choices=[('active', '正常运行'), ('internal_test', '内部测试'), ('in_progress', '开发中'), ('pending', '待确认'), ('paused', '暂停维护'), ('retired', '已下线'), ('archived', '历史资料')], default='active', max_length=24, verbose_name='状态')),
                ('url', models.CharField(blank=True, max_length=600, verbose_name='入口地址')),
                ('link_label', models.CharField(default='打开入口', max_length=40, verbose_name='入口文字')),
                ('is_visible', models.BooleanField(default=True, verbose_name='显示')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='internal_portal.businessarea', verbose_name='所属板块')),
                ('owners', models.ManyToManyField(blank=True, related_name='portal_entries', to='internal_portal.teammember', verbose_name='负责人')),
            ],
            options={
                'verbose_name': '门户条目',
                'verbose_name_plural': '门户条目',
                'ordering': ('area__sort_order', 'sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='businessarea',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='business_areas', to='internal_portal.teammember', verbose_name='负责人'),
        ),
    ]
