# Generated by Django 5.2.16 on 2026-07-28 00:32

from django.db import migrations


def seed_portal(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    ProjectProfile = apps.get_model('internal_portal', 'ProjectProfile')
    TeamMember = apps.get_model('internal_portal', 'TeamMember')
    BusinessArea = apps.get_model('internal_portal', 'BusinessArea')
    PortalEntry = apps.get_model('internal_portal', 'PortalEntry')

    Group.objects.get_or_create(name='internal_portal')

    ProjectProfile.objects.get_or_create(
        pk=1,
        defaults={
            'title': '章鱼智学项目中心',
            'positioning': (
                '围绕章鱼智学学习产品与圆明智学内容体系，持续推进产品开发、'
                '内容建设和用户服务。'
            ),
            'current_phase': '学生端持续完善，内容体系同步建设',
            'current_focus': '稳定学习产品体验\n完善题库与讲义内容\n保持对外内容持续更新',
        },
    )

    member_data = [
        ('柯恩', '技术；自媒体可视化视频', 10),
        ('史谨毓', '自媒体可视化视频', 20),
        ('张誉宝', '自媒体免费系统课', 30),
        ('尹竹', '自媒体学习经验分享', 40),
    ]
    members = {}
    for name, responsibility, order in member_data:
        member, _ = TeamMember.objects.get_or_create(
            name=name,
            defaults={
                'responsibility': responsibility,
                'sort_order': order,
            },
        )
        members[name] = member

    area_data = [
        (
            'product', '产品与用户',
            '学生端产品、下载安装、用户支持与法律信息。',
            ['柯恩'], 10,
        ),
        (
            'content', '内容与品牌',
            '题库讲义、圆明智学内容方向、官网与品牌资产。',
            ['史谨毓', '柯恩', '张誉宝', '尹竹'], 20,
        ),
        (
            'technology', '技术与数据',
            '客户端、服务端、数据、测试、发布和运维资料。',
            ['柯恩'], 30,
        ),
        (
            'team', '团队与记录',
            '团队分工、项目文档和协作边界。',
            ['柯恩', '史谨毓', '张誉宝', '尹竹'], 40,
        ),
    ]
    areas = {}
    for slug, name, summary, owner_names, order in area_data:
        area, _ = BusinessArea.objects.get_or_create(
            slug=slug,
            defaults={
                'name': name,
                'summary': summary,
                'sort_order': order,
            },
        )
        area.owners.set(members[name] for name in owner_names)
        areas[slug] = area

    gitee = 'https://gitee.com/annouimo/zhangyuzhixue-v2'
    entries = [
        ('product', '学生端 Android', 'download', 'Android 内部测试安装包。',
         'internal_test', f'{gitee}/releases/download/v1.1.0-beta.3/app-release.apk',
         '下载 APK', ['柯恩'], 10),
        ('product', '学生端 Windows', 'download', 'Windows 内部测试安装程序。',
         'internal_test', (
             f'{gitee}/releases/download/v1.1.0-beta.3/'
             '%E7%AB%A0%E9%B1%BC%E6%99%BA%E5%AD%A6-1.1.0-beta.3-windows.exe'
         ), '下载安装包', ['柯恩'], 20),
        ('product', '学生端 iOS', 'download', '通过 TestFlight 加入内部测试。',
         'internal_test', 'https://testflight.apple.com/join/tg29y4wF',
         '打开 TestFlight', ['柯恩'], 30),
        ('product', '产品介绍与下载', 'product', '官网软件介绍、功能截图和下载说明。',
         'active', '/software.html', '查看官网', ['柯恩'], 40),
        ('product', '隐私政策', 'document', '产品个人信息处理和用户权利说明。',
         'active', '/privacy.html', '查看政策', ['柯恩'], 50),
        ('product', '用户协议', 'document', '章鱼智学软件与服务使用约定。',
         'active', '/terms.html', '查看协议', ['柯恩'], 60),

        ('content', '圆明智学内容主页', 'media', '集中展示各内容平台入口。',
         'active', '/media.html', '查看内容主页', ['史谨毓', '柯恩', '张誉宝', '尹竹'], 10),
        ('content', '哔哩哔哩', 'media', '圆明智学视频内容。',
         'active', 'https://b23.tv/64D6X7S', '访问主页',
         ['史谨毓', '柯恩', '张誉宝', '尹竹'], 20),
        ('content', '小红书', 'media', '圆明智学图文与视频内容。',
         'active', 'https://xhslink.cn/m/7yhO5z9sbjR', '访问主页',
         ['史谨毓', '柯恩', '张誉宝', '尹竹'], 30),
        ('content', '抖音', 'media', '圆明智学短视频内容。',
         'active', 'https://v.douyin.com/BZl4YGhfE0E/', '访问主页',
         ['史谨毓', '柯恩', '张誉宝', '尹竹'], 40),
        ('content', '微信视频号', 'media', '在微信视频号搜索“圆明智学”。',
         'active', '/media.html', '查看搜索说明',
         ['史谨毓', '柯恩', '张誉宝', '尹竹'], 50),
        ('content', '官网品牌口径', 'document', '官网、海报与公开宣传的统一表达基线。',
         'active', f'{gitee}/blob/master/docs/00-%E6%95%B4%E4%BD%93%E6%83%85%E5%86%B5/'
         '%E5%AE%98%E7%BD%91%E5%93%81%E7%89%8C%E5%8F%A3%E5%BE%84%E5%9F%BA%E7%BA%BF_V1.0.md',
         '在 Gitee 查看', ['柯恩'], 60),

        ('technology', 'Gitee 主仓库', 'tool', '代码、版本历史和技术文档的统一来源。',
         'active', gitee, '打开仓库', ['柯恩'], 10),
        ('technology', '架构概览', 'document', '系统分层、核心数据流和架构原则。',
         'active', f'{gitee}/blob/master/docs/01-%E6%9E%B6%E6%9E%84/'
         '%E6%9E%B6%E6%9E%84%E6%A6%82%E8%A7%88.md',
         '在 Gitee 查看', ['柯恩'], 20),
        ('technology', '服务端架构', 'document', 'Django API、Admin、数据和部署设计。',
         'active', f'{gitee}/blob/master/docs/03-%E6%9C%8D%E5%8A%A1%E7%AB%AF/'
         '%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%9E%B6%E6%9E%84.md',
         '在 Gitee 查看', ['柯恩'], 30),
        ('technology', '测试运行手册', 'document', '服务端、Flutter 与集成测试运行方法。',
         'active', f'{gitee}/blob/master/docs/07-%E5%B7%A5%E4%BD%9C%E6%B5%81/'
         '%E6%B5%8B%E8%AF%95%E8%BF%90%E8%A1%8C%E6%89%8B%E5%86%8C.md',
         '在 Gitee 查看', ['柯恩'], 40),
        ('technology', '开发工作流程', 'document', '代码、设计与发布协作约定。',
         'active', f'{gitee}/blob/master/docs/07-%E5%B7%A5%E4%BD%9C%E6%B5%81/'
         '%E5%BC%80%E5%8F%91%E5%B7%A5%E4%BD%9C%E6%B5%81%E7%A8%8B.md',
         '在 Gitee 查看', ['柯恩'], 50),
        ('technology', 'API 文档', 'tool', '当前服务端 OpenAPI 与 Swagger 页面。',
         'active', '/api/v1/docs/swagger/', '打开 API 文档', ['柯恩'], 60),
        ('technology', 'Django 管理后台', 'tool', '内容与系统数据管理入口，仅限授权管理员。',
         'active', '/admin/', '打开管理后台', ['柯恩'], 70),

        ('team', '设计文档索引', 'document', '架构、数据、UI、服务端和工作流文档总入口。',
         'active', f'{gitee}/blob/master/docs/00-%E6%95%B4%E4%BD%93%E6%83%85%E5%86%B5/README.md',
         '在 Gitee 查看', ['柯恩'], 10),
        ('team', '页面导航', 'document', '学生端主要页面及导航关系。',
         'active', f'{gitee}/blob/master/docs/01-%E6%9E%B6%E6%9E%84/'
         '%E9%A1%B5%E9%9D%A2%E5%AF%BC%E8%88%AA.md',
         '在 Gitee 查看', ['柯恩'], 20),
    ]

    for (
        area_slug, name, entry_type, description, status, url,
        link_label, owner_names, order,
    ) in entries:
        entry, _ = PortalEntry.objects.get_or_create(
            area=areas[area_slug],
            name=name,
            defaults={
                'entry_type': entry_type,
                'description': description,
                'status': status,
                'url': url,
                'link_label': link_label,
                'sort_order': order,
            },
        )
        entry.owners.set(members[name] for name in owner_names)


class Migration(migrations.Migration):

    dependencies = [
        ('internal_portal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_portal, migrations.RunPython.noop),
    ]
