# Generated by Django 5.2.16 on 2026-07-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='年份')),
                ('exam_type', models.CharField(blank=True, default='', max_length=32, verbose_name='考试类型')),
                ('region', models.CharField(blank=True, default='', max_length=32, verbose_name='地区')),
                ('number', models.CharField(blank=True, default='', max_length=16, verbose_name='题号')),
                ('question_type', models.CharField(choices=[('choice', '选择题'), ('fill', '填空题'), ('solution', '解答题')], max_length=16, verbose_name='题型')),
                ('difficulty', models.FloatField(blank=True, null=True, verbose_name='困难度')),
                ('calculation', models.FloatField(blank=True, null=True, verbose_name='计算量')),
                ('stem', models.TextField(verbose_name='题干（不含img标签）')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='配图路径列表')),
                ('default_score', models.FloatField(blank=True, null=True, verbose_name='参考分值')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '知识卡片',
                'verbose_name_plural': '知识卡片',
            },
        ),
        migrations.CreateModel(
            name='SolutionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(blank=True, help_text='null=唯一解法', max_length=64, null=True, verbose_name='解法名称')),
                ('source', models.CharField(blank=True, default='', max_length=32, verbose_name='来源')),
                ('sort_order', models.IntegerField(verbose_name='排序')),
            ],
            options={
                'verbose_name': '解法',
                'verbose_name_plural': '解法',
                'ordering': ['sub_question', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceExt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.JSONField(help_text='{"A":"...","B":"...","C":"...","D":"..."}', verbose_name='选项')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choice_ext', to='qbank.basequestion')),
            ],
            options={
                'verbose_name': '选择题选项',
                'verbose_name_plural': '选择题选项',
            },
        ),
        migrations.CreateModel(
            name='ConceptTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='标签名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='qbank.concepttag')),
            ],
            options={
                'verbose_name': '概念标签',
                'verbose_name_plural': '概念标签',
            },
        ),
        migrations.CreateModel(
            name='QuestionConceptTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_questions', to='qbank.concepttag')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_concept_tags', to='qbank.basequestion')),
            ],
            options={
                'verbose_name': '题目-概念标签',
                'verbose_name_plural': '题目-概念标签',
            },
        ),
        migrations.AddField(
            model_name='basequestion',
            name='concept_tags',
            field=models.ManyToManyField(blank=True, related_name='questions', through='qbank.QuestionConceptTag', to='qbank.concepttag'),
        ),
        migrations.CreateModel(
            name='QuestionKnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_questions', to='qbank.knowledgecard')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_knowledge_cards', to='qbank.basequestion')),
            ],
            options={
                'verbose_name': '题目-知识卡片',
                'verbose_name_plural': '题目-知识卡片',
            },
        ),
        migrations.AddField(
            model_name='basequestion',
            name='knowledge_cards',
            field=models.ManyToManyField(blank=True, related_name='questions', through='qbank.QuestionKnowledgeCard', to='qbank.knowledgecard'),
        ),
        migrations.CreateModel(
            name='SolutionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='步骤编号')),
                ('title', models.CharField(max_length=128, verbose_name='步骤标题')),
                ('content', models.TextField(verbose_name='步骤内容（含LaTeX）')),
                ('card_titles', models.JSONField(blank=True, default=list, verbose_name='关联知识卡片标题')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_steps', to='qbank.solutionmethod')),
            ],
            options={
                'verbose_name': '解题步骤',
                'verbose_name_plural': '解题步骤',
                'ordering': ['method', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.TextField(blank=True, null=True, verbose_name='小题题干')),
                ('answer', models.TextField(blank=True, default='', verbose_name='正确答案')),
                ('sort_order', models.IntegerField(verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='qbank.subquestion')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='qbank.basequestion')),
            ],
            options={
                'verbose_name': '小题',
                'verbose_name_plural': '小题',
                'ordering': ['question', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='solutionmethod',
            name='sub_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_methods', to='qbank.subquestion'),
        ),
        migrations.AddConstraint(
            model_name='questionconcepttag',
            constraint=models.UniqueConstraint(fields=('question', 'concept_tag'), name='uq_question_concept_tag'),
        ),
        migrations.AddConstraint(
            model_name='questionknowledgecard',
            constraint=models.UniqueConstraint(fields=('question', 'knowledge_card'), name='uq_question_knowledge_card'),
        ),
    ]
