# Generated by Django 5.2.16 on 2026-07-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_knowledgecard_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecard',
            name='category',
            field=models.CharField(choices=[('流程', '流程'), ('定理', '定理')], max_length=16, verbose_name='分类'),
        ),
    ]
