# Generated by Django 5.2.16 on 2026-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_alter_knowledgecard_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='explanation',
            field=models.TextField(blank=True, default='', verbose_name='解析'),
        ),
    ]
