# Generated by Django 5.2.16 on 2026-07-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
        ('qbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('filter_snapshot', models.JSONField(blank=True, default=dict, verbose_name='筛选条件快照')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_papers', to='accounts.student')),
            ],
            options={
                'verbose_name': '组卷',
                'verbose_name_plural': '组卷',
            },
        ),
        migrations.CreateModel(
            name='CustomPaperQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(verbose_name='排序')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='interactions.custompaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='qbank.basequestion')),
            ],
            options={
                'verbose_name': '组卷-题目',
                'verbose_name_plural': '组卷-题目',
                'ordering': ['paper', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='custompaper',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='custom_papers', through='interactions.CustomPaperQuestion', to='qbank.basequestion'),
        ),
        migrations.CreateModel(
            name='PaperLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='interactions.custompaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_likes', to='accounts.student')),
            ],
            options={
                'verbose_name': '组卷点赞',
                'verbose_name_plural': '组卷点赞',
            },
        ),
        migrations.CreateModel(
            name='QuestionRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty_score', models.IntegerField(verbose_name='困难度评分')),
                ('calculation_score', models.IntegerField(verbose_name='计算量评分')),
                ('elegance_score', models.IntegerField(verbose_name='优美度评分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='qbank.basequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='accounts.student')),
            ],
            options={
                'verbose_name': '题目评分',
                'verbose_name_plural': '题目评分',
            },
        ),
        migrations.CreateModel(
            name='StudentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='courses.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.student')),
            ],
            options={
                'verbose_name': '提交头',
                'verbose_name_plural': '提交头',
            },
        ),
        migrations.CreateModel(
            name='SubmissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='第几次作答')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成')], default='in_progress', max_length=16, verbose_name='状态')),
                ('answer_text', models.TextField(blank=True, default='', verbose_name='学生答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='是否正确')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_details', to='qbank.basequestion')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='interactions.studentsubmission')),
            ],
            options={
                'verbose_name': '提交明细',
                'verbose_name_plural': '提交明细',
            },
        ),
        migrations.CreateModel(
            name='StepFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_question_index', models.IntegerField(default=0, verbose_name='小题索引')),
                ('method_id', models.IntegerField(blank=True, null=True, verbose_name='解法ID')),
                ('step_number', models.IntegerField(verbose_name='步骤编号')),
                ('status', models.CharField(choices=[('full_correct', '全对'), ('partial_correct', '过程对计算错'), ('wrong', '不会')], max_length=32, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_feedbacks', to='qbank.basequestion')),
                ('submission_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_feedbacks', to='interactions.submissiondetail')),
            ],
            options={
                'verbose_name': '步骤反馈',
                'verbose_name_plural': '步骤反馈',
            },
        ),
        migrations.CreateModel(
            name='CardFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=128, verbose_name='卡片标题')),
                ('card_status', models.CharField(choices=[('mastered', '完全掌握'), ('understood', '了解'), ('not_understood', '不了解')], max_length=32, verbose_name='掌握程度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_feedbacks', to='qbank.basequestion')),
                ('submission_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_feedbacks', to='interactions.submissiondetail')),
            ],
            options={
                'verbose_name': '卡片反馈',
                'verbose_name_plural': '卡片反馈',
            },
        ),
        migrations.AddConstraint(
            model_name='custompaperquestion',
            constraint=models.UniqueConstraint(fields=('paper', 'question'), name='uq_paper_question'),
        ),
        migrations.AddConstraint(
            model_name='paperlike',
            constraint=models.UniqueConstraint(fields=('student', 'paper'), name='uq_student_paper_like'),
        ),
        migrations.AddConstraint(
            model_name='questionrating',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='uq_student_question_rating'),
        ),
    ]
