# Generated by Django 5.2.16 on 2026-07-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_student_id'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collects', to='interactions.custompaper')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_collects', to='accounts.student')),
            ],
            options={
                'verbose_name': '组卷收藏',
                'verbose_name_plural': '组卷收藏',
                'constraints': [models.UniqueConstraint(fields=('student', 'paper'), name='uq_student_paper_collect')],
            },
        ),
    ]
