# Generated by Django 5.2.16 on 2026-07-11 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_papercollect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSatisfactionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(blank=True, default='', max_length=500, verbose_name='页面URL')),
                ('rating', models.IntegerField(verbose_name='评分(1-5)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='评价内容')),
                ('device_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '退出评价反馈',
                'verbose_name_plural': '退出评价反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
