# Generated by Django 5.2.16 on 2026-07-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_name'),
        ('interactions', '0003_pagesatisfactionfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='预设名称')),
                ('years', models.TextField(blank=True, default='', verbose_name='年份(JSON list)')),
                ('regions', models.TextField(blank=True, default='', verbose_name='地区(JSON list)')),
                ('concept_tags', models.TextField(blank=True, default='', verbose_name='概念标签(JSON list)')),
                ('types', models.TextField(blank=True, default='', verbose_name='考试类型(JSON list)')),
                ('knowledge_cards', models.TextField(blank=True, default='', verbose_name='知识卡片(JSON list)')),
                ('question_types', models.TextField(blank=True, default='', verbose_name='题型(JSON list)')),
                ('diff_min', models.FloatField(blank=True, null=True, verbose_name='难度下限')),
                ('diff_max', models.FloatField(blank=True, null=True, verbose_name='难度上限')),
                ('calc_min', models.FloatField(blank=True, null=True, verbose_name='计算量下限')),
                ('calc_max', models.FloatField(blank=True, null=True, verbose_name='计算量上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_filters', to='accounts.student')),
            ],
            options={
                'verbose_name': '筛选预设',
                'verbose_name_plural': '筛选预设',
            },
        ),
    ]
