# Generated by Django 5.2.16 on 2026-07-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_name'),
        ('interactions', '0004_preferencefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencefilter',
            name='client_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='客户端本地ID'),
        ),
        migrations.AlterUniqueTogether(
            name='preferencefilter',
            unique_together={('student', 'client_id')},
        ),
    ]
