# Generated by Django 5.2.16 on 2026-07-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_preferencefilter_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsubmission',
            name='assignment',
        ),
    ]
