# Generated by Django 5.2.16 on 2026-07-28 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_accountdeletionrequest_previous_class_group_and_more'),
        ('interactions', '0006_remove_studentsubmission_assignment'),
        ('qbank', '0006_normalize_fill_answer_blanks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('new_question', '新题投稿'), ('question_correction', '题目纠错')], max_length=32, verbose_name='贡献类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('needs_revision', '待修改'), ('processing', '处理中'), ('completed', '已完成'), ('rejected', '未采纳'), ('withdrawn', '已撤回')], db_index=True, default='pending', max_length=24, verbose_name='状态')),
                ('review_note', models.TextField(blank=True, default='', verbose_name='当前审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_contributions', to='qbank.basequestion', verbose_name='处理后题目')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correction_contributions', to='qbank.basequestion', verbose_name='纠错题目')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_contributions', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_contributions', to='accounts.student')),
            ],
            options={
                'verbose_name': '内容贡献',
                'verbose_name_plural': '内容贡献审核',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', '已提交'), ('resubmitted', '重新提交'), ('needs_revision', '打回修改'), ('processing', '进入处理'), ('completed', '处理完成'), ('rejected', '未采纳'), ('withdrawn', '已撤回')], max_length=24, verbose_name='操作')),
                ('note', models.TextField(blank=True, default='', verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_contribution_actions', to=settings.AUTH_USER_MODEL)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='interactions.contentcontribution')),
            ],
            options={
                'verbose_name': '贡献审核记录',
                'verbose_name_plural': '贡献审核记录',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionTagSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_name', models.CharField(max_length=64, verbose_name='建议名称')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='建议理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('created', '已创建'), ('merged', '已合并'), ('rejected', '未采纳')], default='pending', max_length=16, verbose_name='状态')),
                ('reviewer_note', models.CharField(blank=True, default='', max_length=500, verbose_name='审核说明')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_suggestions', to='interactions.contentcontribution')),
                ('resolved_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tag_suggestions', to='qbank.concepttag', verbose_name='处理后标签')),
                ('suggested_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tag_suggestions', to='qbank.concepttag', verbose_name='建议上级标签')),
            ],
            options={
                'verbose_name': '新标签建议',
                'verbose_name_plural': '新标签建议',
            },
        ),
        migrations.CreateModel(
            name='ContributionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='修订版本')),
                ('raw_json', models.TextField(blank=True, default='', verbose_name='原始 JSON')),
                ('normalized_payload', models.JSONField(default=dict, verbose_name='规范化内容')),
                ('question_snapshot', models.JSONField(blank=True, default=dict, verbose_name='原题快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='interactions.contentcontribution')),
            ],
            options={
                'verbose_name': '贡献修订',
                'verbose_name_plural': '贡献修订',
                'ordering': ['contribution', '-revision_number'],
                'constraints': [models.UniqueConstraint(fields=('contribution', 'revision_number'), name='uq_contribution_revision_number')],
            },
        ),
        migrations.CreateModel(
            name='ContributionTagSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_selections', to='qbank.concepttag')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_selections', to='interactions.contentcontribution')),
            ],
            options={
                'verbose_name': '贡献标签',
                'verbose_name_plural': '贡献标签',
                'constraints': [models.UniqueConstraint(fields=('contribution', 'concept_tag'), name='uq_contribution_concept_tag')],
            },
        ),
    ]
