version: '1.0'
name: zhangyuzhixue-ci
displayName: zhangyuzhixue-ci
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: flutter-check
    displayName: flutter-check
    steps:
      - step: shell
        run: cd flutter_app && dart analyze
      - step: shell
        run: cd flutter_app && flutter test

  - name: django-check
    displayName: django-check
    steps:
      - step: shell
        run: cd server && pip install -r requirements.txt -q
      - step: shell
        run: flake8 --config server/.flake8 server/
      - step: shell
        run: cd server && python manage.py check --deploy
      - step: shell
        run: cd server && python manage.py makemigrations --check
