version: '1.0'
name: zhangyuzhixue-ci
displayName: zhangyuzhixue-ci
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: flutter-check
    displayName: flutter-check
    steps:
      - step: shell@agent
        displayName: dart analyze
        inputs:
          command: dart analyze
          workDir: flutter_app
      - step: shell@agent
        displayName: flutter test
        inputs:
          command: flutter test
          workDir: flutter_app

  - name: django-check
    displayName: django-check
    steps:
      - step: shell@agent
        displayName: install deps
        inputs:
          command: pip install -r requirements.txt -q
          workDir: server
      - step: shell@agent
        displayName: flake8
        inputs:
          command: flake8 --config .flake8 server/
          workDir: server
      - step: shell@agent
        displayName: check --deploy
        inputs:
          command: python manage.py check --deploy
          workDir: server
      - step: shell@agent
        displayName: makemigrations --check
        inputs:
          command: python manage.py makemigrations --check
          workDir: server
