# Generated by Django 5.2.16 on 2026-07-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='编码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=256, null=True, verbose_name='图标URL')),
                ('icon_emoji', models.CharField(blank=True, max_length=16, null=True, verbose_name='图标emoji')),
                ('category', models.CharField(choices=[('LOGIN', '登录'), ('PRACTICE', '练习'), ('COURSE', '课程'), ('PAPER', '组卷'), ('RATING', '评分')], max_length=32, verbose_name='分类')),
                ('category_label', models.CharField(blank=True, max_length=32, null=True, verbose_name='分类标签')),
                ('display_order', models.IntegerField(default=0, verbose_name='展示顺序')),
                ('trigger_type', models.CharField(blank=True, choices=[('LOGIN_STREAK', '连续登录'), ('PRACTICE_COUNT', '做题数量'), ('COURSE_COMPLETE', '课程完成'), ('PAPER_COUNT', '组卷数量'), ('RATING_COUNT', '评分数量')], max_length=32, null=True, verbose_name='触发类型')),
                ('threshold', models.IntegerField(default=0, verbose_name='达成阈值')),
            ],
            options={
                'verbose_name': '成就定义',
                'verbose_name_plural': '成就定义',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DbVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('qbank', '题库'), ('lecture', '讲义')], max_length=16, unique=True, verbose_name='数据库类型')),
                ('schema_version', models.IntegerField(default=1, verbose_name='Schema版本')),
                ('data_version', models.IntegerField(default=1, verbose_name='数据版本')),
                ('checksum', models.CharField(blank=True, default='', max_length=128, verbose_name='SHA256校验和')),
                ('size_bytes', models.IntegerField(default=0, verbose_name='文件大小')),
                ('download_url', models.CharField(blank=True, default='', max_length=256, verbose_name='下载路径')),
                ('force_update', models.BooleanField(default=False, verbose_name='强制更新')),
                ('message', models.CharField(blank=True, default='', max_length=256, verbose_name='更新说明')),
                ('built_at', models.DateTimeField(blank=True, null=True, verbose_name='构建时间')),
            ],
            options={
                'verbose_name': '数据库版本',
                'verbose_name_plural': '数据库版本',
            },
        ),
        migrations.CreateModel(
            name='LevelConfig',
            fields=[
                ('level', models.IntegerField(primary_key=True, serialize=False, verbose_name='等级')),
                ('min_xp', models.IntegerField(verbose_name='最小累计积分')),
                ('title', models.CharField(max_length=64, verbose_name='等级名称')),
                ('icon_emoji', models.CharField(blank=True, max_length=16, null=True, verbose_name='图标emoji')),
            ],
            options={
                'verbose_name': '等级配置',
                'verbose_name_plural': '等级配置',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=16, verbose_name='平台')),
                ('version_name', models.CharField(max_length=32, verbose_name='版本名')),
                ('version_code', models.IntegerField(verbose_name='版本号')),
                ('force_update', models.BooleanField(default=False, verbose_name='强制更新')),
                ('download_url', models.URLField(blank=True, default='', max_length=512, verbose_name='下载地址')),
                ('release_notes', models.TextField(blank=True, default='', verbose_name='更新说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'App版本',
                'verbose_name_plural': 'App版本',
                'constraints': [models.UniqueConstraint(fields=('platform', 'version_code'), name='uq_platform_version_code')],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='金额（正=收入，负=支出）')),
                ('transaction_type', models.CharField(choices=[('EARN', '收入'), ('SPEND', '支出')], max_length=16, verbose_name='类型')),
                ('source', models.CharField(choices=[('LOGIN_BONUS', '签到'), ('PRACTICE_REWARD', '做题奖励'), ('TASK_REWARD', '完成任务'), ('SIGNUP_BONUS', '新人赠送'), ('PAPER_PURCHASE', '组卷消费'), ('REVIEW_REWARD', '退出评价奖励'), ('ADMIN_ADJUST', '管理员调整')], max_length=32, verbose_name='来源')),
                ('source_object_id', models.IntegerField(blank=True, null=True, verbose_name='关联业务ID')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='accounts.student')),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='进度')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='已解锁')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='解锁时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='system.achievementdef')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='accounts.student')),
            ],
            options={
                'verbose_name': '学生成就',
                'verbose_name_plural': '学生成就',
                'constraints': [models.UniqueConstraint(fields=('student', 'achievement'), name='uq_student_achievement')],
            },
        ),
    ]
