# Generated by Django 5.2.16 on 2026-07-10 10:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbversion',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='dbversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='dbversion',
            name='download_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='下载路径'),
        ),
        migrations.AlterField(
            model_name='dbversion',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='更新说明'),
        ),
    ]
