# Generated by Django 5.2.16 on 2026-07-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_dbversion_created_at_dbversion_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemToolsProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '系统工具',
                'verbose_name_plural': '系统工具',
                'managed': False,
            },
        ),
    ]
