# Generated by Django 5.2.16 on 2026-07-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_systemtoolsproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminHelpProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '管理员使用说明',
                'verbose_name_plural': '管理员使用说明',
                'managed': False,
            },
        ),
    ]
