# Generated by Django 5.2.16 on 2026-07-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_adminhelpproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementdef',
            name='category',
            field=models.CharField(choices=[('LOGIN', '登录'), ('PRACTICE', '练习'), ('STREAK', '毅力'), ('ACCURACY', '精确度'), ('PAPER', '组卷'), ('RATING', '评分')], max_length=32, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='achievementdef',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('LOGIN_STREAK', '连续登录'), ('PRACTICE_COUNT', '做题数量'), ('PRACTICE_STREAK', '连续做题'), ('ACCURACY_RATE', '正确率'), ('CONSECUTIVE_CORRECT', '连续正确'), ('PAPER_COUNT', '组卷数量'), ('RATING_COUNT', '评分数量')], max_length=32, null=True, verbose_name='触发类型'),
        ),
    ]
