# Generated by Django 5.2.16 on 2026-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_achievementdef_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='amount',
            field=models.FloatField(verbose_name='金额（正=收入，负=支出）（分）'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='source',
            field=models.CharField(choices=[('LOGIN_BONUS', '签到'), ('PRACTICE_REWARD', '做题奖励'), ('TASK_REWARD', '完成任务'), ('SIGNUP_BONUS', '新人赠送'), ('PAPER_PURCHASE', '组卷消费'), ('REVIEW_REWARD', '退出评价奖励'), ('RATING_REWARD', '题目评价奖励'), ('ADMIN_ADJUST', '管理员调整')], max_length=32, verbose_name='来源'),
        ),
    ]
