# Generated by Django 5.2.16 on 2026-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_alter_pointstransaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='client_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='客户端ID'),
        ),
    ]
