# Generated by Django 5.2.16 on 2026-07-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_points_transaction_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbversion',
            name='image_checksum',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='配图SHA256校验和'),
        ),
        migrations.AddField(
            model_name='dbversion',
            name='image_download_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='配图下载路径'),
        ),
        migrations.AddField(
            model_name='dbversion',
            name='image_size_bytes',
            field=models.IntegerField(default=0, verbose_name='配图包大小'),
        ),
    ]
